# -*- coding: utf-8 -*-

################################################################################
## Form generated from reading UI file 'autonlainaussovellus.ui'
##
## Created by: Qt User Interface Compiler version 6.8.0
##
## WARNING! All changes made in this file will be lost when recompiling UI file!
################################################################################

from PySide6.QtCore import (QCoreApplication, QDate, QDateTime, QLocale,
    QMetaObject, QObject, QPoint, QRect,
    QSize, QTime, QUrl, Qt)
from PySide6.QtGui import (QBrush, QColor, QConicalGradient, QCursor,
    QFont, QFontDatabase, QGradient, QIcon,
    QImage, QKeySequence, QLinearGradient, QPainter,
    QPalette, QPixmap, QRadialGradient, QTransform)
from PySide6.QtWidgets import (QApplication, QLabel, QLineEdit, QMainWindow,
    QMenuBar, QSizePolicy, QStatusBar, QTabWidget,
    QWidget)
import autonhaku_rc
import kuvat_rc

class Ui_MainWindow(object):
    def setupUi(self, MainWindow):
        if not MainWindow.objectName():
            MainWindow.setObjectName(u"MainWindow")
        MainWindow.resize(456, 701)
        self.centralwidget = QWidget(MainWindow)
        self.centralwidget.setObjectName(u"centralwidget")
        self.centralwidget.setStyleSheet(u"background-color: rgb(223, 32, 112);")
        self.tabWidget = QTabWidget(self.centralwidget)
        self.tabWidget.setObjectName(u"tabWidget")
        self.tabWidget.setGeometry(QRect(0, 0, 891, 651))
        self.tabWidget.setStyleSheet(u"background-color: rgb(0, 33, 72);\n"
"background-color: rgb(223, 32, 112);")
        self.tab = QWidget()
        self.tab.setObjectName(u"tab")
        self.tab.setStyleSheet(u"background-color: rgb(223, 32, 112);")
        self.tabWidget_2 = QTabWidget(self.tab)
        self.tabWidget_2.setObjectName(u"tabWidget_2")
        self.tabWidget_2.setGeometry(QRect(-10, -60, 461, 701))
        self.tabWidget_2.setStyleSheet(u"background-color: rgb(0, 33, 72);")
        self.tab_3 = QWidget()
        self.tab_3.setObjectName(u"tab_3")
        self.autoKuvaLabel = QLabel(self.tab_3)
        self.autoKuvaLabel.setObjectName(u"autoKuvaLabel")
        self.autoKuvaLabel.setGeometry(QRect(270, 110, 140, 210))
        self.autoKuvaLabel.setPixmap(QPixmap(u":/kuvat/auto.png"))
        self.autoKuvaLabel.setAlignment(Qt.AlignmentFlag.AlignCenter)
        self.lainaajaKuvaLabel = QLabel(self.tab_3)
        self.lainaajaKuvaLabel.setObjectName(u"lainaajaKuvaLabel")
        self.lainaajaKuvaLabel.setGeometry(QRect(20, 110, 140, 210))
        self.lainaajaKuvaLabel.setPixmap(QPixmap(u":/kuvat/human.png"))
        self.lainaajaKuvaLabel.setAlignment(Qt.AlignmentFlag.AlignCenter)
        self.lainausAikaKuva = QLabel(self.tab_3)
        self.lainausAikaKuva.setObjectName(u"lainausAikaKuva")
        self.lainausAikaKuva.setGeometry(QRect(270, 460, 140, 140))
        self.lainausAikaKuva.setPixmap(QPixmap(u":/kuvat/clock.png"))
        self.lainausAikaKuva.setAlignment(Qt.AlignmentFlag.AlignCenter)
        self.lainauspivKuvaLabel = QLabel(self.tab_3)
        self.lainauspivKuvaLabel.setObjectName(u"lainauspivKuvaLabel")
        self.lainauspivKuvaLabel.setGeometry(QRect(10, 460, 171, 151))
        self.lainauspivKuvaLabel.setPixmap(QPixmap(u":/kuvat/calender.png"))
        self.lainausOtsikkoLabel = QLabel(self.tab_3)
        self.lainausOtsikkoLabel.setObjectName(u"lainausOtsikkoLabel")
        self.lainausOtsikkoLabel.setGeometry(QRect(120, 40, 231, 31))
        font = QFont()
        font.setPointSize(22)
        self.lainausOtsikkoLabel.setFont(font)
        self.lainausOtsikkoLabel.setStyleSheet(u"color: rgb(75, 188, 197);")
        self.ajokorttiLineEdit = QLineEdit(self.tab_3)
        self.ajokorttiLineEdit.setObjectName(u"ajokorttiLineEdit")
        self.ajokorttiLineEdit.setGeometry(QRect(20, 330, 161, 31))
        font1 = QFont()
        font1.setPointSize(11)
        self.ajokorttiLineEdit.setFont(font1)
        self.ajokorttiLineEdit.setStyleSheet(u"color: rgb(75, 188, 197);")
        self.ajokorttiLabel = QLabel(self.tab_3)
        self.ajokorttiLabel.setObjectName(u"ajokorttiLabel")
        self.ajokorttiLabel.setGeometry(QRect(20, 380, 161, 31))
        self.ajokorttiLabel.setFont(font1)
        self.ajokorttiLabel.setStyleSheet(u"color: rgb(75, 188, 197);")
        self.avainLineEdit = QLineEdit(self.tab_3)
        self.avainLineEdit.setObjectName(u"avainLineEdit")
        self.avainLineEdit.setGeometry(QRect(260, 330, 181, 31))
        self.avainLineEdit.setFont(font1)
        self.avainLineEdit.setStyleSheet(u"color: rgb(75, 188, 197);")
        self.avainLabel = QLabel(self.tab_3)
        self.avainLabel.setObjectName(u"avainLabel")
        self.avainLabel.setGeometry(QRect(270, 380, 161, 31))
        self.avainLabel.setFont(font1)
        self.avainLabel.setStyleSheet(u"color: rgb(75, 188, 197);")
        self.pivamaaraLabel = QLabel(self.tab_3)
        self.pivamaaraLabel.setObjectName(u"pivamaaraLabel")
        self.pivamaaraLabel.setGeometry(QRect(10, 620, 161, 21))
        self.pivamaaraLabel.setFont(font1)
        self.pivamaaraLabel.setStyleSheet(u"color: rgb(75, 188, 197);")
        self.aikaLabel = QLabel(self.tab_3)
        self.aikaLabel.setObjectName(u"aikaLabel")
        self.aikaLabel.setGeometry(QRect(260, 620, 161, 21))
        self.aikaLabel.setFont(font1)
        self.aikaLabel.setStyleSheet(u"color: rgb(75, 188, 197);")
        self.lainausPivLabel = QLabel(self.tab_3)
        self.lainausPivLabel.setObjectName(u"lainausPivLabel")
        self.lainausPivLabel.setGeometry(QRect(30, 430, 131, 20))
        font2 = QFont()
        font2.setPointSize(14)
        self.lainausPivLabel.setFont(font2)
        self.lainausPivLabel.setStyleSheet(u"color: rgb(75, 188, 197);")
        self.LainausAikaLabel = QLabel(self.tab_3)
        self.LainausAikaLabel.setObjectName(u"LainausAikaLabel")
        self.LainausAikaLabel.setGeometry(QRect(280, 430, 131, 20))
        self.LainausAikaLabel.setFont(font2)
        self.LainausAikaLabel.setStyleSheet(u"color: rgb(75, 188, 197);")
        self.lainaajaLabel = QLabel(self.tab_3)
        self.lainaajaLabel.setObjectName(u"lainaajaLabel")
        self.lainaajaLabel.setGeometry(QRect(30, 80, 131, 21))
        self.lainaajaLabel.setFont(font2)
        self.lainaajaLabel.setStyleSheet(u"color: rgb(75, 188, 197);")
        self.autoLainausLabel = QLabel(self.tab_3)
        self.autoLainausLabel.setObjectName(u"autoLainausLabel")
        self.autoLainausLabel.setGeometry(QRect(300, 80, 61, 20))
        self.autoLainausLabel.setFont(font2)
        self.autoLainausLabel.setStyleSheet(u"color: rgb(75, 188, 197);")
        self.tabWidget_2.addTab(self.tab_3, "")
        self.tab_4 = QWidget()
        self.tab_4.setObjectName(u"tab_4")
        self.label_12 = QLabel(self.tab_4)
        self.label_12.setObjectName(u"label_12")
        self.label_12.setGeometry(QRect(40, 20, 161, 221))
        self.label_12.setPixmap(QPixmap(u":/kuvat/auto.png"))
        self.label_13 = QLabel(self.tab_4)
        self.label_13.setObjectName(u"label_13")
        self.label_13.setGeometry(QRect(440, 150, 151, 161))
        self.label_13.setPixmap(QPixmap(u":/kuvat/calender.png"))
        self.label_14 = QLabel(self.tab_4)
        self.label_14.setObjectName(u"label_14")
        self.label_14.setGeometry(QRect(290, 310, 151, 151))
        self.label_14.setPixmap(QPixmap(u":/kuvat/clock.png"))
        self.tabWidget_2.addTab(self.tab_4, "")
        self.tabWidget.addTab(self.tab, "")
        self.tab_2 = QWidget()
        self.tab_2.setObjectName(u"tab_2")
        self.tab_2.setStyleSheet(u"background-color: rgb(0, 33, 72);")
        self.autoLainausKuvaLabel = QLabel(self.tab_2)
        self.autoLainausKuvaLabel.setObjectName(u"autoLainausKuvaLabel")
        self.autoLainausKuvaLabel.setGeometry(QRect(130, 70, 161, 221))
        self.autoLainausKuvaLabel.setPixmap(QPixmap(u":/kuvat/auto.png"))
        self.palautusPaivaKuvaLabel = QLabel(self.tab_2)
        self.palautusPaivaKuvaLabel.setObjectName(u"palautusPaivaKuvaLabel")
        self.palautusPaivaKuvaLabel.setGeometry(QRect(40, 420, 151, 161))
        self.palautusPaivaKuvaLabel.setPixmap(QPixmap(u":/kuvat/calender.png"))
        self.palutusAikaKuvaLabel = QLabel(self.tab_2)
        self.palutusAikaKuvaLabel.setObjectName(u"palutusAikaKuvaLabel")
        self.palutusAikaKuvaLabel.setGeometry(QRect(250, 420, 151, 151))
        self.palutusAikaKuvaLabel.setPixmap(QPixmap(u":/kuvat/clock.png"))
        self.palautusOtsikkoLabel = QLabel(self.tab_2)
        self.palautusOtsikkoLabel.setObjectName(u"palautusOtsikkoLabel")
        self.palautusOtsikkoLabel.setGeometry(QRect(120, 0, 251, 31))
        self.palautusOtsikkoLabel.setFont(font)
        self.palautusOtsikkoLabel.setStyleSheet(u"color: rgb(75, 188, 197);")
        self.autoPalautusLabel = QLabel(self.tab_2)
        self.autoPalautusLabel.setObjectName(u"autoPalautusLabel")
        self.autoPalautusLabel.setGeometry(QRect(180, 40, 80, 20))
        self.autoPalautusLabel.setFont(font2)
        self.autoPalautusLabel.setStyleSheet(u"color: rgb(75, 188, 197);")
        self.viivakoodiLineEdit = QLineEdit(self.tab_2)
        self.viivakoodiLineEdit.setObjectName(u"viivakoodiLineEdit")
        self.viivakoodiLineEdit.setGeometry(QRect(120, 300, 181, 31))
        self.viivakoodiLineEdit.setFont(font1)
        self.viivakoodiLineEdit.setStyleSheet(u"color: rgb(75, 188, 197);")
        self.viivakoodiLabel = QLabel(self.tab_2)
        self.viivakoodiLabel.setObjectName(u"viivakoodiLabel")
        self.viivakoodiLabel.setGeometry(QRect(120, 350, 181, 21))
        self.viivakoodiLabel.setFont(font1)
        self.viivakoodiLabel.setStyleSheet(u"color: rgb(75, 188, 197);")
        self.palutusPaivaLabel = QLabel(self.tab_2)
        self.palutusPaivaLabel.setObjectName(u"palutusPaivaLabel")
        self.palutusPaivaLabel.setGeometry(QRect(50, 390, 131, 21))
        self.palutusPaivaLabel.setFont(font2)
        self.palutusPaivaLabel.setStyleSheet(u"color: rgb(75, 188, 197);")
        self.palautusLabel = QLabel(self.tab_2)
        self.palautusLabel.setObjectName(u"palautusLabel")
        self.palautusLabel.setGeometry(QRect(30, 590, 161, 21))
        self.palautusLabel.setFont(font1)
        self.palautusLabel.setStyleSheet(u"color: rgb(75, 188, 197);")
        self.palautusAikaOtsikkoLabel = QLabel(self.tab_2)
        self.palautusAikaOtsikkoLabel.setObjectName(u"palautusAikaOtsikkoLabel")
        self.palautusAikaOtsikkoLabel.setGeometry(QRect(270, 390, 131, 20))
        self.palautusAikaOtsikkoLabel.setFont(font2)
        self.palautusAikaOtsikkoLabel.setStyleSheet(u"color: rgb(75, 188, 197);")
        self.palautusAikaLabel = QLabel(self.tab_2)
        self.palautusAikaLabel.setObjectName(u"palautusAikaLabel")
        self.palautusAikaLabel.setGeometry(QRect(240, 590, 161, 21))
        self.palautusAikaLabel.setFont(font1)
        self.palautusAikaLabel.setStyleSheet(u"color: rgb(75, 188, 197);")
        self.tabWidget.addTab(self.tab_2, "")
        MainWindow.setCentralWidget(self.centralwidget)
        self.menubar = QMenuBar(MainWindow)
        self.menubar.setObjectName(u"menubar")
        self.menubar.setGeometry(QRect(0, 0, 456, 33))
        self.menubar.setStyleSheet(u"background-color: rgb(0, 33, 72);\n"
"color: rgb(75, 188, 197);")
        MainWindow.setMenuBar(self.menubar)
        self.statusbar = QStatusBar(MainWindow)
        self.statusbar.setObjectName(u"statusbar")
        self.statusbar.setStyleSheet(u"background-color: rgb(223, 32, 112);")
        MainWindow.setStatusBar(self.statusbar)

        self.retranslateUi(MainWindow)

        self.tabWidget.setCurrentIndex(0)
        self.tabWidget_2.setCurrentIndex(0)


        QMetaObject.connectSlotsByName(MainWindow)
    # setupUi

    def retranslateUi(self, MainWindow):
        MainWindow.setWindowTitle(QCoreApplication.translate("MainWindow", u"MainWindow", None))
        self.autoKuvaLabel.setText("")
        self.lainaajaKuvaLabel.setText("")
        self.lainausAikaKuva.setText("")
        self.lainauspivKuvaLabel.setText("")
        self.lainausOtsikkoLabel.setText(QCoreApplication.translate("MainWindow", u"AUTON LAINAUS", None))
        self.ajokorttiLineEdit.setText("")
        self.ajokorttiLineEdit.setPlaceholderText(QCoreApplication.translate("MainWindow", u"Lue ajokortti", None))
        self.ajokorttiLabel.setText("")
        self.avainLineEdit.setText("")
        self.avainLineEdit.setPlaceholderText(QCoreApplication.translate("MainWindow", u"Lue avaimen viivakoodi", None))
        self.avainLabel.setText("")
        self.pivamaaraLabel.setText("")
        self.aikaLabel.setText("")
        self.lainausPivLabel.setText(QCoreApplication.translate("MainWindow", u"Lainaus p\u00e4iv\u00e4", None))
        self.LainausAikaLabel.setText(QCoreApplication.translate("MainWindow", u"Lainaus aika", None))
        self.lainaajaLabel.setText(QCoreApplication.translate("MainWindow", u"Lainaaja", None))
        self.autoLainausLabel.setText(QCoreApplication.translate("MainWindow", u"Auto", None))
        self.tabWidget_2.setTabText(self.tabWidget_2.indexOf(self.tab_3), QCoreApplication.translate("MainWindow", u"Tab 1", None))
        self.label_12.setText("")
        self.label_13.setText("")
        self.label_14.setText("")
        self.tabWidget_2.setTabText(self.tabWidget_2.indexOf(self.tab_4), QCoreApplication.translate("MainWindow", u"Tab 2", None))
        self.tabWidget.setTabText(self.tabWidget.indexOf(self.tab), QCoreApplication.translate("MainWindow", u"Lainaus", None))
        self.autoLainausKuvaLabel.setText("")
        self.palautusPaivaKuvaLabel.setText("")
        self.palutusAikaKuvaLabel.setText("")
        self.palautusOtsikkoLabel.setText(QCoreApplication.translate("MainWindow", u"AUTON PALAUTUS", None))
        self.autoPalautusLabel.setText(QCoreApplication.translate("MainWindow", u"Auto", None))
        self.viivakoodiLineEdit.setText("")
        self.viivakoodiLineEdit.setPlaceholderText(QCoreApplication.translate("MainWindow", u"Lue avaimen viivakoodi", None))
        self.viivakoodiLabel.setText("")
        self.palutusPaivaLabel.setText(QCoreApplication.translate("MainWindow", u"Palautus p\u00e4iv\u00e4", None))
        self.palautusLabel.setText("")
        self.palautusAikaOtsikkoLabel.setText(QCoreApplication.translate("MainWindow", u"Palautus aika", None))
        self.palautusAikaLabel.setText("")
        self.tabWidget.setTabText(self.tabWidget.indexOf(self.tab_2), QCoreApplication.translate("MainWindow", u"Palautus", None))
    # retranslateUi

