# -*- coding: utf-8 -*-

################################################################################
## Form generated from reading UI file 'autonlainaussovellusidea.ui'
##
## Created by: Qt User Interface Compiler version 6.8.0
##
## WARNING! All changes made in this file will be lost when recompiling UI file!
################################################################################

from PySide6.QtCore import (QCoreApplication, QDate, QDateTime, QLocale,
    QMetaObject, QObject, QPoint, QRect,
    QSize, QTime, QUrl, Qt)
from PySide6.QtGui import (QBrush, QColor, QConicalGradient, QCursor,
    QFont, QFontDatabase, QGradient, QIcon,
    QImage, QKeySequence, QLinearGradient, QPainter,
    QPalette, QPixmap, QRadialGradient, QTransform)
from PySide6.QtWidgets import (QApplication, QLabel, QLineEdit, QMainWindow,
    QMenuBar, QSizePolicy, QStatusBar, QTabWidget,
    QWidget)
import kuvat_rc

class Ui_MainWindow(object):
    def setupUi(self, MainWindow):
        if not MainWindow.objectName():
            MainWindow.setObjectName(u"MainWindow")
        MainWindow.resize(446, 762)
        self.centralwidget = QWidget(MainWindow)
        self.centralwidget.setObjectName(u"centralwidget")
        self.centralwidget.setStyleSheet(u"background-color: rgb(223, 32, 112);")
        self.tabWidget = QTabWidget(self.centralwidget)
        self.tabWidget.setObjectName(u"tabWidget")
        self.tabWidget.setGeometry(QRect(0, 0, 451, 900))
        font = QFont()
        font.setPointSize(26)
        self.tabWidget.setFont(font)
        self.tabWidget.setStyleSheet(u"background-color: rgb(223, 32, 112);")
        self.takeTab = QWidget()
        self.takeTab.setObjectName(u"takeTab")
        self.takeTab.setStyleSheet(u"background-color: rgb(0, 33, 72);")
        self.takeTitleLabel = QLabel(self.takeTab)
        self.takeTitleLabel.setObjectName(u"takeTitleLabel")
        self.takeTitleLabel.setGeometry(QRect(100, 20, 231, 31))
        font1 = QFont()
        font1.setPointSize(22)
        self.takeTitleLabel.setFont(font1)
        self.takeTitleLabel.setStyleSheet(u"color: rgb(75, 188, 197);")
        self.borrowerLabel = QLabel(self.takeTab)
        self.borrowerLabel.setObjectName(u"borrowerLabel")
        self.borrowerLabel.setGeometry(QRect(50, 70, 131, 21))
        font2 = QFont()
        font2.setPointSize(14)
        self.borrowerLabel.setFont(font2)
        self.borrowerLabel.setStyleSheet(u"color: rgb(75, 188, 197);")
        self.humanLabel = QLabel(self.takeTab)
        self.humanLabel.setObjectName(u"humanLabel")
        self.humanLabel.setGeometry(QRect(30, 100, 140, 210))
        self.humanLabel.setPixmap(QPixmap(u":/kuvat/human.png"))
        self.humanLabel.setAlignment(Qt.AlignmentFlag.AlignCenter)
        self.licenseLineEdit = QLineEdit(self.takeTab)
        self.licenseLineEdit.setObjectName(u"licenseLineEdit")
        self.licenseLineEdit.setGeometry(QRect(20, 320, 161, 31))
        font3 = QFont()
        font3.setPointSize(11)
        self.licenseLineEdit.setFont(font3)
        self.licenseLineEdit.setStyleSheet(u"color: rgb(75, 188, 197);")
        self.licenseLabel = QLabel(self.takeTab)
        self.licenseLabel.setObjectName(u"licenseLabel")
        self.licenseLabel.setGeometry(QRect(20, 370, 161, 31))
        self.licenseLabel.setFont(font3)
        self.licenseLabel.setStyleSheet(u"color: rgb(75, 188, 197);")
        self.takeDateLabel = QLabel(self.takeTab)
        self.takeDateLabel.setObjectName(u"takeDateLabel")
        self.takeDateLabel.setGeometry(QRect(30, 420, 131, 20))
        self.takeDateLabel.setFont(font2)
        self.takeDateLabel.setStyleSheet(u"color: rgb(75, 188, 197);")
        self.calenderLabel = QLabel(self.takeTab)
        self.calenderLabel.setObjectName(u"calenderLabel")
        self.calenderLabel.setGeometry(QRect(20, 450, 171, 151))
        self.calenderLabel.setPixmap(QPixmap(u":/kuvat/calender.png"))
        self.dateLabel = QLabel(self.takeTab)
        self.dateLabel.setObjectName(u"dateLabel")
        self.dateLabel.setGeometry(QRect(20, 610, 161, 21))
        self.dateLabel.setFont(font3)
        self.dateLabel.setStyleSheet(u"color: rgb(75, 188, 197);")
        self.carTakeLabel = QLabel(self.takeTab)
        self.carTakeLabel.setObjectName(u"carTakeLabel")
        self.carTakeLabel.setGeometry(QRect(290, 70, 61, 20))
        self.carTakeLabel.setFont(font2)
        self.carTakeLabel.setStyleSheet(u"color: rgb(75, 188, 197);")
        self.carKeysLabel = QLabel(self.takeTab)
        self.carKeysLabel.setObjectName(u"carKeysLabel")
        self.carKeysLabel.setGeometry(QRect(240, 100, 140, 210))
        self.carKeysLabel.setPixmap(QPixmap(u":/kuvat/auto.png"))
        self.carKeysLabel.setAlignment(Qt.AlignmentFlag.AlignCenter)
        self.keysLineEdit = QLineEdit(self.takeTab)
        self.keysLineEdit.setObjectName(u"keysLineEdit")
        self.keysLineEdit.setGeometry(QRect(220, 320, 181, 31))
        self.keysLineEdit.setFont(font3)
        self.keysLineEdit.setStyleSheet(u"color: rgb(75, 188, 197);")
        self.keysLabel = QLabel(self.takeTab)
        self.keysLabel.setObjectName(u"keysLabel")
        self.keysLabel.setGeometry(QRect(230, 370, 161, 31))
        self.keysLabel.setFont(font3)
        self.keysLabel.setStyleSheet(u"color: rgb(75, 188, 197);")
        self.takeTimeLabel = QLabel(self.takeTab)
        self.takeTimeLabel.setObjectName(u"takeTimeLabel")
        self.takeTimeLabel.setGeometry(QRect(250, 420, 131, 20))
        self.takeTimeLabel.setFont(font2)
        self.takeTimeLabel.setStyleSheet(u"color: rgb(75, 188, 197);")
        self.clockKuva = QLabel(self.takeTab)
        self.clockKuva.setObjectName(u"clockKuva")
        self.clockKuva.setGeometry(QRect(250, 450, 140, 140))
        self.clockKuva.setPixmap(QPixmap(u":/kuvat/clock.png"))
        self.clockKuva.setAlignment(Qt.AlignmentFlag.AlignCenter)
        self.timeLabel = QLabel(self.takeTab)
        self.timeLabel.setObjectName(u"timeLabel")
        self.timeLabel.setGeometry(QRect(240, 610, 161, 21))
        self.timeLabel.setFont(font3)
        self.timeLabel.setStyleSheet(u"color: rgb(75, 188, 197);")
        self.tabWidget.addTab(self.takeTab, "")
        self.returnTab = QWidget()
        self.returnTab.setObjectName(u"returnTab")
        font4 = QFont()
        font4.setPointSize(9)
        self.returnTab.setFont(font4)
        self.returnTab.setStyleSheet(u"background-color: rgb(0, 33, 72);")
        self.carLabel = QLabel(self.returnTab)
        self.carLabel.setObjectName(u"carLabel")
        self.carLabel.setGeometry(QRect(130, 70, 161, 221))
        self.carLabel.setPixmap(QPixmap(u":/kuvat/auto.png"))
        self.returnCalanderPicLabel = QLabel(self.returnTab)
        self.returnCalanderPicLabel.setObjectName(u"returnCalanderPicLabel")
        self.returnCalanderPicLabel.setGeometry(QRect(40, 420, 151, 161))
        self.returnCalanderPicLabel.setPixmap(QPixmap(u":/kuvat/calender.png"))
        self.clockPicLabel = QLabel(self.returnTab)
        self.clockPicLabel.setObjectName(u"clockPicLabel")
        self.clockPicLabel.setGeometry(QRect(250, 420, 151, 151))
        self.clockPicLabel.setPixmap(QPixmap(u":/kuvat/clock.png"))
        self.returnCar = QLabel(self.returnTab)
        self.returnCar.setObjectName(u"returnCar")
        self.returnCar.setGeometry(QRect(120, 0, 251, 31))
        self.returnCar.setFont(font1)
        self.returnCar.setStyleSheet(u"color: rgb(75, 188, 197);")
        self.carReturn = QLabel(self.returnTab)
        self.carReturn.setObjectName(u"carReturn")
        self.carReturn.setGeometry(QRect(180, 40, 80, 20))
        self.carReturn.setFont(font2)
        self.carReturn.setStyleSheet(u"color: rgb(75, 188, 197);")
        self.ddsLineEdit = QLineEdit(self.returnTab)
        self.ddsLineEdit.setObjectName(u"ddsLineEdit")
        self.ddsLineEdit.setGeometry(QRect(120, 300, 181, 31))
        self.ddsLineEdit.setFont(font3)
        self.ddsLineEdit.setStyleSheet(u"color: rgb(75, 188, 197);")
        self.ddsLabel = QLabel(self.returnTab)
        self.ddsLabel.setObjectName(u"ddsLabel")
        self.ddsLabel.setGeometry(QRect(120, 350, 181, 21))
        self.ddsLabel.setFont(font3)
        self.ddsLabel.setStyleSheet(u"color: rgb(75, 188, 197);")
        self.returnDateLabel = QLabel(self.returnTab)
        self.returnDateLabel.setObjectName(u"returnDateLabel")
        self.returnDateLabel.setGeometry(QRect(50, 390, 131, 21))
        self.returnDateLabel.setFont(font2)
        self.returnDateLabel.setStyleSheet(u"color: rgb(75, 188, 197);")
        self.returnCalenderLabel = QLabel(self.returnTab)
        self.returnCalenderLabel.setObjectName(u"returnCalenderLabel")
        self.returnCalenderLabel.setGeometry(QRect(30, 590, 161, 21))
        self.returnCalenderLabel.setFont(font3)
        self.returnCalenderLabel.setStyleSheet(u"color: rgb(75, 188, 197);")
        self.returnTimeLabel = QLabel(self.returnTab)
        self.returnTimeLabel.setObjectName(u"returnTimeLabel")
        self.returnTimeLabel.setGeometry(QRect(270, 390, 131, 20))
        self.returnTimeLabel.setFont(font2)
        self.returnTimeLabel.setStyleSheet(u"color: rgb(75, 188, 197);")
        self.returnHourLabel = QLabel(self.returnTab)
        self.returnHourLabel.setObjectName(u"returnHourLabel")
        self.returnHourLabel.setGeometry(QRect(240, 590, 161, 21))
        self.returnHourLabel.setFont(font3)
        self.returnHourLabel.setStyleSheet(u"color: rgb(75, 188, 197);")
        self.tabWidget.addTab(self.returnTab, "")
        MainWindow.setCentralWidget(self.centralwidget)
        self.menubar = QMenuBar(MainWindow)
        self.menubar.setObjectName(u"menubar")
        self.menubar.setGeometry(QRect(0, 0, 446, 33))
        self.menubar.setStyleSheet(u"background-color: rgb(0, 33, 72);\n"
"color: rgb(75, 188, 197);")
        MainWindow.setMenuBar(self.menubar)
        self.statusbar = QStatusBar(MainWindow)
        self.statusbar.setObjectName(u"statusbar")
        font5 = QFont()
        font5.setPointSize(10)
        self.statusbar.setFont(font5)
        self.statusbar.setStyleSheet(u"background-color: rgb(223, 32, 112);")
        self.statusbar.setSizeGripEnabled(True)
        MainWindow.setStatusBar(self.statusbar)
        QWidget.setTabOrder(self.tabWidget, self.licenseLineEdit)
        QWidget.setTabOrder(self.licenseLineEdit, self.keysLineEdit)
        QWidget.setTabOrder(self.keysLineEdit, self.ddsLineEdit)

        self.retranslateUi(MainWindow)

        self.tabWidget.setCurrentIndex(0)


        QMetaObject.connectSlotsByName(MainWindow)
    # setupUi

    def retranslateUi(self, MainWindow):
        MainWindow.setWindowTitle(QCoreApplication.translate("MainWindow", u"MainWindow", None))
        self.takeTitleLabel.setText(QCoreApplication.translate("MainWindow", u"AUTON LAINAUS", None))
        self.borrowerLabel.setText(QCoreApplication.translate("MainWindow", u"Lainaaja", None))
        self.humanLabel.setText("")
        self.licenseLineEdit.setText("")
        self.licenseLineEdit.setPlaceholderText(QCoreApplication.translate("MainWindow", u"Lue ajokortti", None))
        self.licenseLabel.setText("")
        self.takeDateLabel.setText(QCoreApplication.translate("MainWindow", u"Lainaus p\u00e4iv\u00e4", None))
        self.calenderLabel.setText("")
        self.dateLabel.setText("")
        self.carTakeLabel.setText(QCoreApplication.translate("MainWindow", u"Auto", None))
        self.carKeysLabel.setText("")
        self.keysLineEdit.setText("")
        self.keysLineEdit.setPlaceholderText(QCoreApplication.translate("MainWindow", u"Lue avaimen viivakoodi", None))
        self.keysLabel.setText("")
        self.takeTimeLabel.setText(QCoreApplication.translate("MainWindow", u"Lainaus aika", None))
        self.clockKuva.setText("")
        self.timeLabel.setText("")
        self.tabWidget.setTabText(self.tabWidget.indexOf(self.takeTab), QCoreApplication.translate("MainWindow", u"Lainaus", None))
        self.carLabel.setText("")
        self.returnCalanderPicLabel.setText("")
        self.clockPicLabel.setText("")
        self.returnCar.setText(QCoreApplication.translate("MainWindow", u"AUTON PALAUTUS", None))
        self.carReturn.setText(QCoreApplication.translate("MainWindow", u"Auto", None))
        self.ddsLineEdit.setText("")
        self.ddsLineEdit.setPlaceholderText(QCoreApplication.translate("MainWindow", u"Lue avaimen viivakoodi", None))
        self.ddsLabel.setText("")
        self.returnDateLabel.setText(QCoreApplication.translate("MainWindow", u"Palautus p\u00e4iv\u00e4", None))
        self.returnCalenderLabel.setText("")
        self.returnTimeLabel.setText(QCoreApplication.translate("MainWindow", u"Palautus aika", None))
        self.returnHourLabel.setText("")
        self.tabWidget.setTabText(self.tabWidget.indexOf(self.returnTab), QCoreApplication.translate("MainWindow", u"Palautus", None))
    # retranslateUi

