# -*- coding: utf-8 -*-

################################################################################
## Form generated from reading UI file 'user.ui'
##
## Created by: Qt User Interface Compiler version 6.8.0
##
## WARNING! All changes made in this file will be lost when recompiling UI file!
################################################################################

from PySide6.QtCore import (QCoreApplication, QDate, QDateTime, QLocale,
    QMetaObject, QObject, QPoint, QRect,
    QSize, QTime, QUrl, Qt)
from PySide6.QtGui import (QBrush, QColor, QConicalGradient, QCursor,
    QFont, QFontDatabase, QGradient, QIcon,
    QImage, QKeySequence, QLinearGradient, QPainter,
    QPalette, QPixmap, QRadialGradient, QTransform)
from PySide6.QtWidgets import (QApplication, QLabel, QLineEdit, QMainWindow,
    QMenuBar, QPushButton, QSizePolicy, QStatusBar,
    QTabWidget, QWidget)
import userUiRescources_rc

class Ui_MainWindow(object):
    def setupUi(self, MainWindow):
        if not MainWindow.objectName():
            MainWindow.setObjectName(u"MainWindow")
        MainWindow.resize(447, 810)
        self.centralwidget = QWidget(MainWindow)
        self.centralwidget.setObjectName(u"centralwidget")
        self.centralwidget.setStyleSheet(u"background-color: rgb(223, 32, 112);")
        self.tabWidget = QTabWidget(self.centralwidget)
        self.tabWidget.setObjectName(u"tabWidget")
        self.tabWidget.setGeometry(QRect(0, 0, 451, 900))
        font = QFont()
        font.setPointSize(26)
        self.tabWidget.setFont(font)
        self.tabWidget.setStyleSheet(u"background-color: rgb(223, 32, 112);")
        self.takeTab = QWidget()
        self.takeTab.setObjectName(u"takeTab")
        self.takeTab.setStyleSheet(u"background-color: rgb(0, 33, 72);")
        self.borrowerLabel = QLabel(self.takeTab)
        self.borrowerLabel.setObjectName(u"borrowerLabel")
        self.borrowerLabel.setGeometry(QRect(50, 90, 131, 31))
        font1 = QFont()
        font1.setPointSize(18)
        self.borrowerLabel.setFont(font1)
        self.borrowerLabel.setStyleSheet(u"color: rgb(75, 188, 197);")
        self.humanLabel = QLabel(self.takeTab)
        self.humanLabel.setObjectName(u"humanLabel")
        self.humanLabel.setGeometry(QRect(30, 140, 140, 210))
        self.humanLabel.setPixmap(QPixmap(u":/pictures/uiPictrues/human.png"))
        self.humanLabel.setAlignment(Qt.AlignmentFlag.AlignCenter)
        self.licenseLineEdit = QLineEdit(self.takeTab)
        self.licenseLineEdit.setObjectName(u"licenseLineEdit")
        self.licenseLineEdit.setGeometry(QRect(20, 360, 161, 41))
        self.licenseLineEdit.setFont(font1)
        self.licenseLineEdit.setStyleSheet(u"color: rgb(75, 188, 197);")
        self.takeDateLabel = QLabel(self.takeTab)
        self.takeDateLabel.setObjectName(u"takeDateLabel")
        self.takeDateLabel.setGeometry(QRect(20, 410, 151, 31))
        self.takeDateLabel.setFont(font1)
        self.takeDateLabel.setStyleSheet(u"color: rgb(75, 188, 197);")
        self.calenderLabel = QLabel(self.takeTab)
        self.calenderLabel.setObjectName(u"calenderLabel")
        self.calenderLabel.setGeometry(QRect(20, 450, 171, 151))
        self.calenderLabel.setPixmap(QPixmap(u":/pictures/uiPictrues/calender.png"))
        self.dateLabel = QLabel(self.takeTab)
        self.dateLabel.setObjectName(u"dateLabel")
        self.dateLabel.setGeometry(QRect(30, 610, 111, 21))
        self.dateLabel.setFont(font1)
        self.dateLabel.setStyleSheet(u"color: rgb(75, 188, 197);")
        self.carTakeLabel = QLabel(self.takeTab)
        self.carTakeLabel.setObjectName(u"carTakeLabel")
        self.carTakeLabel.setGeometry(QRect(280, 90, 61, 31))
        self.carTakeLabel.setFont(font1)
        self.carTakeLabel.setStyleSheet(u"color: rgb(75, 188, 197);")
        self.carKeysLabel = QLabel(self.takeTab)
        self.carKeysLabel.setObjectName(u"carKeysLabel")
        self.carKeysLabel.setGeometry(QRect(240, 140, 140, 210))
        self.carKeysLabel.setPixmap(QPixmap(u":/pictures/uiPictrues/auto.png"))
        self.carKeysLabel.setAlignment(Qt.AlignmentFlag.AlignCenter)
        self.keysLineEdit = QLineEdit(self.takeTab)
        self.keysLineEdit.setObjectName(u"keysLineEdit")
        self.keysLineEdit.setGeometry(QRect(220, 360, 181, 41))
        self.keysLineEdit.setFont(font1)
        self.keysLineEdit.setStyleSheet(u"color: rgb(75, 188, 197);")
        self.takeTimeLabel = QLabel(self.takeTab)
        self.takeTimeLabel.setObjectName(u"takeTimeLabel")
        self.takeTimeLabel.setGeometry(QRect(250, 410, 131, 31))
        self.takeTimeLabel.setFont(font1)
        self.takeTimeLabel.setStyleSheet(u"color: rgb(75, 188, 197);")
        self.clockPictureLabel = QLabel(self.takeTab)
        self.clockPictureLabel.setObjectName(u"clockPictureLabel")
        self.clockPictureLabel.setGeometry(QRect(250, 450, 140, 140))
        self.clockPictureLabel.setPixmap(QPixmap(u":/pictures/uiPictrues/clock.png"))
        self.clockPictureLabel.setAlignment(Qt.AlignmentFlag.AlignCenter)
        self.timeLabel = QLabel(self.takeTab)
        self.timeLabel.setObjectName(u"timeLabel")
        self.timeLabel.setGeometry(QRect(290, 600, 61, 21))
        self.timeLabel.setFont(font1)
        self.timeLabel.setStyleSheet(u"color: rgb(75, 188, 197);")
        self.takeCarPushButton = QPushButton(self.takeTab)
        self.takeCarPushButton.setObjectName(u"takeCarPushButton")
        self.takeCarPushButton.setGeometry(QRect(130, 0, 181, 91))
        font2 = QFont()
        font2.setPointSize(20)
        self.takeCarPushButton.setFont(font2)
        self.takeCarPushButton.setStyleSheet(u"color: rgb(75, 188, 197);")
        self.soundsOnPushButton = QPushButton(self.takeTab)
        self.soundsOnPushButton.setObjectName(u"soundsOnPushButton")
        self.soundsOnPushButton.setGeometry(QRect(350, 0, 75, 81))
        icon = QIcon()
        icon.addFile(u":/pictures/uiPictrues/soundsOn.png", QSize(), QIcon.Mode.Normal, QIcon.State.Off)
        self.soundsOnPushButton.setIcon(icon)
        self.soundsOnPushButton.setIconSize(QSize(70, 70))
        self.soundOffPushButton = QPushButton(self.takeTab)
        self.soundOffPushButton.setObjectName(u"soundOffPushButton")
        self.soundOffPushButton.setGeometry(QRect(350, 0, 75, 81))
        icon1 = QIcon()
        icon1.addFile(u":/pictures/uiPictrues/soundOff.png", QSize(), QIcon.Mode.Normal, QIcon.State.Off)
        self.soundOffPushButton.setIcon(icon1)
        self.soundOffPushButton.setIconSize(QSize(70, 70))
        self.goBackPushButton = QPushButton(self.takeTab)
        self.goBackPushButton.setObjectName(u"goBackPushButton")
        self.goBackPushButton.setGeometry(QRect(160, 640, 101, 51))
        self.goBackPushButton.setFont(font2)
        self.goBackPushButton.setStyleSheet(u"color: rgb(75, 188, 197);")
        self.tabWidget.addTab(self.takeTab, "")
        self.returnTab = QWidget()
        self.returnTab.setObjectName(u"returnTab")
        font3 = QFont()
        font3.setPointSize(9)
        self.returnTab.setFont(font3)
        self.returnTab.setStyleSheet(u"background-color: rgb(0, 33, 72);")
        self.carLabel = QLabel(self.returnTab)
        self.carLabel.setObjectName(u"carLabel")
        self.carLabel.setGeometry(QRect(130, 120, 161, 221))
        self.carLabel.setPixmap(QPixmap(u":/pictures/uiPictrues/auto.png"))
        self.returnCalanderPicLabel = QLabel(self.returnTab)
        self.returnCalanderPicLabel.setObjectName(u"returnCalanderPicLabel")
        self.returnCalanderPicLabel.setGeometry(QRect(40, 450, 151, 161))
        self.returnCalanderPicLabel.setPixmap(QPixmap(u":/pictures/uiPictrues/calender.png"))
        self.clockPicLabel = QLabel(self.returnTab)
        self.clockPicLabel.setObjectName(u"clockPicLabel")
        self.clockPicLabel.setGeometry(QRect(230, 460, 151, 151))
        self.clockPicLabel.setPixmap(QPixmap(u":/pictures/uiPictrues/clock.png"))
        self.carReturnLabel = QLabel(self.returnTab)
        self.carReturnLabel.setObjectName(u"carReturnLabel")
        self.carReturnLabel.setGeometry(QRect(180, 80, 80, 31))
        self.carReturnLabel.setFont(font1)
        self.carReturnLabel.setStyleSheet(u"color: rgb(75, 188, 197);")
        self.ddsLineEdit = QLineEdit(self.returnTab)
        self.ddsLineEdit.setObjectName(u"ddsLineEdit")
        self.ddsLineEdit.setGeometry(QRect(120, 350, 181, 51))
        self.ddsLineEdit.setFont(font1)
        self.ddsLineEdit.setStyleSheet(u"color: rgb(75, 188, 197);")
        self.returnDateLabel = QLabel(self.returnTab)
        self.returnDateLabel.setObjectName(u"returnDateLabel")
        self.returnDateLabel.setGeometry(QRect(40, 410, 161, 31))
        self.returnDateLabel.setFont(font1)
        self.returnDateLabel.setStyleSheet(u"color: rgb(75, 188, 197);")
        self.returnCalenderLabel = QLabel(self.returnTab)
        self.returnCalenderLabel.setObjectName(u"returnCalenderLabel")
        self.returnCalenderLabel.setGeometry(QRect(50, 620, 111, 31))
        self.returnCalenderLabel.setFont(font1)
        self.returnCalenderLabel.setStyleSheet(u"color: rgb(75, 188, 197);")
        self.returnTimeLabel = QLabel(self.returnTab)
        self.returnTimeLabel.setObjectName(u"returnTimeLabel")
        self.returnTimeLabel.setGeometry(QRect(240, 410, 141, 41))
        self.returnTimeLabel.setFont(font1)
        self.returnTimeLabel.setStyleSheet(u"color: rgb(75, 188, 197);")
        self.returnHourLabel = QLabel(self.returnTab)
        self.returnHourLabel.setObjectName(u"returnHourLabel")
        self.returnHourLabel.setGeometry(QRect(270, 620, 61, 21))
        self.returnHourLabel.setFont(font1)
        self.returnHourLabel.setStyleSheet(u"color: rgb(75, 188, 197);")
        self.returnCarPushButton = QPushButton(self.returnTab)
        self.returnCarPushButton.setObjectName(u"returnCarPushButton")
        self.returnCarPushButton.setGeometry(QRect(130, 10, 181, 71))
        self.returnCarPushButton.setFont(font2)
        self.returnCarPushButton.setStyleSheet(u"color: rgb(75, 188, 197);")
        self.soundOnTakePushButton = QPushButton(self.returnTab)
        self.soundOnTakePushButton.setObjectName(u"soundOnTakePushButton")
        self.soundOnTakePushButton.setGeometry(QRect(340, 0, 75, 81))
        self.soundOnTakePushButton.setIcon(icon)
        self.soundOnTakePushButton.setIconSize(QSize(70, 70))
        self.soundsOffTakePushButton = QPushButton(self.returnTab)
        self.soundsOffTakePushButton.setObjectName(u"soundsOffTakePushButton")
        self.soundsOffTakePushButton.setGeometry(QRect(340, 0, 75, 81))
        self.soundsOffTakePushButton.setIcon(icon1)
        self.soundsOffTakePushButton.setIconSize(QSize(70, 70))
        self.goBackTakePushButton = QPushButton(self.returnTab)
        self.goBackTakePushButton.setObjectName(u"goBackTakePushButton")
        self.goBackTakePushButton.setGeometry(QRect(160, 640, 101, 51))
        self.goBackTakePushButton.setFont(font2)
        self.goBackTakePushButton.setStyleSheet(u"color: rgb(75, 188, 197);")
        self.tabWidget.addTab(self.returnTab, "")
        MainWindow.setCentralWidget(self.centralwidget)
        self.menubar = QMenuBar(MainWindow)
        self.menubar.setObjectName(u"menubar")
        self.menubar.setGeometry(QRect(0, 0, 447, 33))
        self.menubar.setStyleSheet(u"background-color: rgb(0, 33, 72);\n"
"color: rgb(75, 188, 197);")
        MainWindow.setMenuBar(self.menubar)
        self.statusbar = QStatusBar(MainWindow)
        self.statusbar.setObjectName(u"statusbar")
        font4 = QFont()
        font4.setPointSize(10)
        self.statusbar.setFont(font4)
        self.statusbar.setStyleSheet(u"background-color: rgb(223, 32, 112);")
        self.statusbar.setSizeGripEnabled(True)
        MainWindow.setStatusBar(self.statusbar)
        QWidget.setTabOrder(self.tabWidget, self.licenseLineEdit)
        QWidget.setTabOrder(self.licenseLineEdit, self.keysLineEdit)
        QWidget.setTabOrder(self.keysLineEdit, self.ddsLineEdit)

        self.retranslateUi(MainWindow)

        self.tabWidget.setCurrentIndex(0)


        QMetaObject.connectSlotsByName(MainWindow)
    # setupUi

    def retranslateUi(self, MainWindow):
        MainWindow.setWindowTitle(QCoreApplication.translate("MainWindow", u"MainWindow", None))
        self.borrowerLabel.setText(QCoreApplication.translate("MainWindow", u"Lainaaja", None))
        self.humanLabel.setText("")
        self.licenseLineEdit.setText("")
        self.licenseLineEdit.setPlaceholderText(QCoreApplication.translate("MainWindow", u"Lue ajokortti", None))
        self.takeDateLabel.setText(QCoreApplication.translate("MainWindow", u"Lainaus p\u00e4iv\u00e4", None))
        self.calenderLabel.setText("")
        self.dateLabel.setText(QCoreApplication.translate("MainWindow", u"27.1.2025", None))
        self.carTakeLabel.setText(QCoreApplication.translate("MainWindow", u"Auto", None))
        self.carKeysLabel.setText("")
        self.keysLineEdit.setText("")
        self.keysLineEdit.setPlaceholderText(QCoreApplication.translate("MainWindow", u"Lue avain", None))
        self.takeTimeLabel.setText(QCoreApplication.translate("MainWindow", u"Lainaus aika", None))
        self.clockPictureLabel.setText("")
        self.timeLabel.setText(QCoreApplication.translate("MainWindow", u"10.09", None))
        self.takeCarPushButton.setText(QCoreApplication.translate("MainWindow", u"Aloita lainaus", None))
        self.soundsOnPushButton.setText("")
        self.soundOffPushButton.setText("")
        self.goBackPushButton.setText(QCoreApplication.translate("MainWindow", u"Nollaa", None))
        self.tabWidget.setTabText(self.tabWidget.indexOf(self.takeTab), QCoreApplication.translate("MainWindow", u"Lainaus", None))
        self.carLabel.setText("")
        self.returnCalanderPicLabel.setText("")
        self.clockPicLabel.setText("")
        self.carReturnLabel.setText(QCoreApplication.translate("MainWindow", u"Auto", None))
        self.ddsLineEdit.setText("")
        self.ddsLineEdit.setPlaceholderText(QCoreApplication.translate("MainWindow", u"Lue avain", None))
        self.returnDateLabel.setText(QCoreApplication.translate("MainWindow", u"Palautus p\u00e4iv\u00e4", None))
        self.returnCalenderLabel.setText(QCoreApplication.translate("MainWindow", u"27.1.2025", None))
        self.returnTimeLabel.setText(QCoreApplication.translate("MainWindow", u"Palautus aika", None))
        self.returnHourLabel.setText(QCoreApplication.translate("MainWindow", u"10.15", None))
        self.returnCarPushButton.setText(QCoreApplication.translate("MainWindow", u"Palauta auto", None))
        self.soundOnTakePushButton.setText("")
        self.soundsOffTakePushButton.setText("")
        self.goBackTakePushButton.setText(QCoreApplication.translate("MainWindow", u"Nollaa", None))
        self.tabWidget.setTabText(self.tabWidget.indexOf(self.returnTab), QCoreApplication.translate("MainWindow", u"Palautus", None))
    # retranslateUi

